SunShineHospital/SunShineHospital/Models/DepartmentViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SunShineHospital.Models
{
    public class DepartmentViewModel
    {
        public int ID { set; get; }

        [Required]
        public string Name { set; get; }

        [Required]
        public string Alias { set; get; }

        public string Description { set; get; }
        public int? ParentID { set; get; }
        public int? DisplayOrder { set; get; }

        [MaxLength(256)]
        public string Image { set; get; }

        public bool? HomeFlag { set; get; }

        public virtual IEnumerable<DoctorViewModel> Doctors { set; get; }
        public virtual IEnumerable<TestViewModel> Tests { set; get; }

        public DateTime? CreatedDate { set; get; }

        public string CreatedBy { set; get; }

        public DateTime? UpdatedDate { set; get; }

        public string UpdatedBy { set; get; }

        [Required]
        public bool Status { set; get; }
    }
}

SunShineHospital/SunShineHospital/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using AutoMapper;
using Microsoft.AspNet.Identity;
using SunShineHospital.Infrastructure.Extensions;
using SunShineHospital.Model.Models;
using SunShineHospital.Models;
using SunShineHospital.Service;

namespace SunShineHospital.Controllers
{
    public class CommentController : Controller
    {
        private ICommentService _commentService;
        public CommentController(ICommentService commentService)
        {
            this._commentService = commentService;
        }
        
        public PartialViewResult Index(int? id)
        {
            return PartialView((int?)id);
        }

        public JsonResult GetComment(int commentId)
        {
            var commentModel = _commentService.GetCommentById(commentId);
            var commentViewModel = Mapper.Map<Comment, CommentViewModel>(commentModel);
            if (commentViewModel != null)
            {
                return Json(new
                {
                    status = true,
                    data = commentViewModel
                }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new
                {
                    status = false
                }, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult GetAll(int doctorId)
        {
            var commentModel = _commentService.GetAllByDoctorId(doctorId);
            var listCommentViewModel = Mapper.Map<IEnumerable<Comment>, IEnumerable<CommentViewModel>>(commentModel);
            return Json(new
            {
                data = listCommentViewModel,
                status = true
            }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult DeleteComment(int commentId)
        {
            var commentModel = _commentService.Delete(commentId);
            if (commentModel != null)
            {
                _commentService.Save();
                return Json(new
                {
                    status = true
                });
            }
            else
            {
                return Json(new
                {
                    status = false
                });
            }
        }

        [HttpPost]
        public JsonResult UpdateComment(string commentViewModel)
        {
            var comment = new JavaScriptSerializer().Deserialize<CommentViewModel>(commentViewModel);
            var commentNew = _commentService.GetCommentById(comment.ID);
            commentNew.Content = comment.Content;
            //bool CheckUserComment(Comment m) => m.UserId == User.Identity.GetUserId();
            if (Request.IsAuthenticated)
            {
                commentNew.UpdatedBy = User.Identity.GetUserName();
                commentNew.UpdatedDate = DateTime.Now;
                _commentService.Update(commentNew);
                _commentService.Save();
                return Json(new
                {
                    status = true
                });
            }
            else
            {
                return Json(new
                {
                    status = false
                });
            }
        }

        [HttpPost]
        public JsonResult CreateComment(string commentViewModel)
        {
            var comment = new JavaScriptSerializer().Deserialize<CommentViewModel>(commentViewModel);
            var commentNew = new Comment();
            commentNew.UpdateComment(comment);
            if (Request.IsAuthenticated)
            {
                commentNew.UserId = User.Identity.GetUserId();
                commentNew.CreatedBy = User.Identity.GetUserName();
                commentNew.CreatedDate = DateTime.Now;
                _commentService.Add(commentNew);
                _commentService.Save();
                return Json(new
                {
                    status = true
                });
            }
            else
            {
                return Json(new
                {
                    status = false
                });
            }
        }
    }
}

SunShineHospital/SunShineHospital/Controllers/DepartmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using SunShineHospital.Model.Models;
using SunShineHospital.Models;
using SunShineHospital.Service;

namespace SunShineHospital.Controllers
{
    public class DepartmentController : Controller
    {
        private IDepartmentService _departmentService;

        public DepartmentController(IDepartmentService departmentService)
        {
            this._departmentService = departmentService;
        }

        public PartialViewResult MenuDepartment()
        {
            var model = _departmentService.GetAll();
            var listDepartmentViewModel = Mapper.Map<IEnumerable<Department>, IEnumerable<DepartmentViewModel>>(model);
            return PartialView(listDepartmentViewModel);
        }
    }
}

SunShineHospital/SunShineHospital/Controllers/DoctorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using Microsoft.AspNet.Identity;
using SunShineHospital.Infrastructure.Core;
using SunShineHospital.Model.Models;
using SunShineHospital.Models;
using SunShineHospital.Service;
using SunShineHospital.Common;
using SunShineHospital.Infrastructure.Extensions;
using SunShineHospital.Web.App_Start;
using Microsoft.AspNet.Identity.Owin;

namespace SunShineHospital.Controllers
{
    public class DoctorController : Controller
    {
        private IDoctorService _doctorService;
        private IDepartmentService _departmentService;
        private ApplicationUserManager _userManager;

        public DoctorController(IDoctorService doctorService, IDepartmentService departmentService, ApplicationUserManager userManager)
        {
            this._doctorService = doctorService;
            this._departmentService = departmentService;
            UserManager = userManager;
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        [HttpGet]
        public ActionResult Register()
        {
            var listDepartmentModel = _departmentService.GetAll();
            var listDepartmentViewModel =
                Mapper.Map<IEnumerable<Department>, IEnumerable<DepartmentViewModel>>(listDepartmentModel);
            IEnumerable<SelectListItem> selectListDepartment = listDepartmentViewModel.OrderBy(m => m.Name).Select(m =>
                new SelectListItem()
                {
                    Value = m.ID.ToString(),
                    Text = m.Name
                });
            ViewBag.listDepartment = selectListDepartment;
            return View();
        }

        [HttpPost]
        public ActionResult Register(DoctorViewModel doctorViewModel)
        {
            if (Request.IsAuthenticated && ModelState.IsValid)
            {
                var user = _userManager.FindById(User.Identity.GetUserId());
                var doctorCheck = _doctorService.GetDoctorIdByUserId(user.Id);
                if (doctorCheck != null)
                {
                    TempData["error"] = string.Format("Xin lỗi, Tài khoản bác sỹ đã tồn tại !");
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    var doctorModel = new Doctor();
                    doctorModel.UpdateDoctor(doctorViewModel);
                    doctorModel.CreatedBy = user.FullName;
                    doctorModel.UserId = user.Id;
                    doctorModel.Salary = 7000000;
                    doctorModel.Image = "Assets/Client/img/doctor.jpg";
                    doctorModel.Alias = GetAliasByName.GetAlias(user.FullName);
                    doctorModel.CreatedDate = DateTime.Now;
                    doctorModel.Status = true;
                    doctorModel.HomeFlag = true;
                    _doctorService.Add(doctorModel);
                    _userManager.AddToRolesAsync(user.Id, new string[] { "Doctor" });
                    _doctorService.Save();
                    TempData["message"] = string.Format("Chaò mừng bạn đã trở thành bác sỹ của chúng tôi !");
                    return RedirectToAction("Index", "Home");
                }
            }
            else
            {
                return View();
            }
        }


        public ActionResult Detail(int id)
        {
            var model = _doctorService.GetById(id);
            var doctorVm = Mapper.Map<Doctor, DoctorViewModel>(model);
            return View(doctorVm);
        }
        public ActionResult Department(int id, int page = 1, string soft = "")
        {
            int pageSize = int.Parse(ConfigHepper.GetByKey("PageSize"));
            var model = _doctorService.GetListDoctorByDepartmentIdPaging(id, page, pageSize, soft, out int totalRow);
            var listDoctor = Mapper.Map<IEnumerable<Doctor>, IEnumerable<DoctorViewModel>>(model);
            int totalPage = (int) Math.Ceiling((double) totalRow / pageSize);
            var department = _departmentService.GetById(id);
            ViewBag.department = Mapper.Map<Department, DepartmentViewModel>(department);

            ViewBag.pageSize = pageSize;
            ViewBag.soft = soft;
            if (totalRow < pageSize)
            {
                ViewBag.count = totalRow;
            }
            else
            {
                ViewBag.count = pageSize;
            }
            var paginationSet = new PaginationSet<DoctorViewModel>()
            {
                Items = listDoctor,
                Page = page,
                TotalCount = totalRow,
                TotalPages = totalPage
            };
            return View(paginationSet);
        }

        public PartialViewResult GetHotDoctor()
        {
            int top = int.Parse(ConfigHepper.GetByKey("TopSize"));
            var model = _doctorService.GetHotDoctor(top);
            var listHotDoctor = Mapper.Map<IEnumerable<Doctor>, IEnumerable<DoctorViewModel>>(model);
            return PartialView(listHotDoctor);
        }

        public ActionResult GetAllDoctor(string keyword = "", int page = 1, string soft = "")
        {
            int pageSize = int.Parse(ConfigHepper.GetByKey("PageSize"));
            var model = _doctorService.Search(keyword, page, pageSize, soft, out int totalRow);
            var doctorViewModel = Mapper.Map<IEnumerable<Doctor>, IEnumerable<DoctorViewModel>>(model);
            int totalPage = (int) Math.Ceiling((double) totalRow / pageSize);
            ViewBag.pageSize = pageSize;
            ViewBag.soft = soft;
            if (totalRow< pageSize)
            {
                ViewBag.count = totalRow;
            }
            else
            {
                ViewBag.count = pageSize;
            }
            var paginationSet = new PaginationSet<DoctorViewModel>()
            {
                Items = doctorViewModel,
                Page = page,
                TotalCount = totalRow,
                TotalPages = totalPage
            };
            return View(paginationSet);
        }
    }
}

SunShineHospital/SunShineHospital/Controllers/RateController.cs
using AutoMapper;
using Microsoft.AspNet.Identity;
using SunShineHospital.Infrastructure.Extensions;
using SunShineHospital.Model.Models;
using SunShineHospital.Models;
using SunShineHospital.Service;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace SunShineHospital.Controllers
{
    public class RateController : Controller
    {
        private IRateService _rateService;

        public RateController(IRateService rateService)
        {
            this._rateService = rateService;
        }

        public PartialViewResult Index(int id)
        {
            ViewBag.doctorId = id;
            return PartialView();
        }

        public PartialViewResult GetDetail(int id)
        {
            var rateDataModel = GetRateData(id);
            ViewBag.doctorId = id;
            ViewBag.averageRate = rateDataModel.AverageRate;
            return PartialView(rateDataModel.ArrayPercent);
        }

        public JsonResult GetRateDetail(int doctorId)
        {
            var rateDataModel = GetRateData(doctorId);
            if (rateDataModel != null)
            {
                return Json(new
                {
                    status = true,
                    data = rateDataModel
                }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new
                {
                    status = true
                }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public JsonResult CreateRate(string rateViewModel)
        {
            var rate = new JavaScriptSerializer().Deserialize<RateViewModel>(rateViewModel);
            var rateNew = new Rate();
            rateNew.UpdateRate(rate);
            if (Request.IsAuthenticated)
            {
                rateNew.UserId = User.Identity.GetUserId();
                var checkRate = _rateService.GetRateByUserId(rateNew.UserId, rateNew.DoctorID);
                if (checkRate != null)
                {
                    checkRate.CountRate = rateNew.CountRate;
                    checkRate.UpdatedBy = User.Identity.GetUserName();
                    checkRate.UpdatedDate = DateTime.Now;
                    _rateService.Update(checkRate);
                }
                else
                {
                    rateNew.CreatedBy = User.Identity.GetUserName();
                    rateNew.CreatedDate = DateTime.Now;
                    _rateService.Add(rateNew);
                }
                _rateService.Save();
                return Json(new
                {
                    status = true
                });
            }
            else
            {
                return Json(new
                {
                    status = false
                });
            }
        }

        private RateData GetRateData(int doctorId)
        {
            var listRate = _rateService.GetAllByDoctorId(doctorId);
            var listRateViewModel = Mapper.Map<IEnumerable<Rate>, IEnumerable<RateViewModel>>(listRate);
            var arrCountRate = new int[5];
            var arrPercent = new float[5];
            float averageRate = 0;
            foreach (var rate in listRateViewModel)
            {
                averageRate += rate.CountRate;
                for (int i = 0; i < 5; i++)
                {
                    if (rate.CountRate == i + 1)
                    {
                        arrCountRate[i] += 1;
                    }
                }
            }

            for (int i = 0; i < 5; i++)
            {
                arrPercent[i] = (float)arrCountRate[i] / listRateViewModel.Count();
                arrPercent[i] *= 100;
            }

            float averageRateModel = (float)averageRate / (listRateViewModel.Count());
            string averageString = averageRateModel.ToString("0.0");
            averageRateModel = float.Parse(averageString, CultureInfo.InvariantCulture.NumberFormat);
            if (Double.IsNaN(averageRateModel))
            {
                averageRateModel = 0;
            }
            var rateData = new RateData()
            {
                AverageRate = averageRateModel,
                ArrayPercent = arrPercent
            };

            return rateData;
        }
    }
}

SunShineHospital/SunShineHospital/Views/Doctor/Department.cshtml
@using SunShineHospital.Infrastructure.Core
@using SunShineHospital.Models
@model PaginationSet<DoctorViewModel>
@{
    ViewBag.Title = "Department";
    var pageSize = ViewBag.pageSize;
    var count = ViewBag.count;
    var soft = ViewBag.soft;
    var department = ViewBag.department;
}

<div id="results">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h4><strong>Xem @count</strong> trong @Model.TotalCount kết quả</h4>
            </div>
            <div class="col-md-6">
                <div class="search_bar_list">
                    <input type="text" class="form-control" placeholder="Ex. Specialist, Name, Doctor...">
                    <input type="submit" value="Search">
                </div>
            </div>
        </div>
    </div>
</div>

<div class="filters_listing">
    <div class="container">
        <ul class="clearfix">
            <li>
                <h6>Sắp xếp theo</h6>
                <select name="orderby" class="selectbox" id="softbydepartment">
                    <option value="?soft=rate">Lượt yêu thích</option>
                    <option value="?soft=popular">Lượt truy cập</option>
                    <option value="?soft=men">BS Nam</option>
                    <option value="?soft=women">BS Nữ</option>
                </select>
            </li>
        </ul>
    </div>
</div>

<div class="container margin_60_35">
    <div class="row">
        <div class="col-lg-12">
            <div class="row">
                @foreach (var doctor in Model.Items)
                {
                    var url = "/" + doctor.Alias + ".doc-" + doctor.ID + ".html";
                    <div class="col-md-4">
                        <div class="box_list wow fadeIn">
                            <a href="#" class="wish_bt"></a>
                            <figure>
                                <a href="@url">
                                    <img src="@doctor.Image" class="img-fluid" alt="">
                                    <div class="preview"><span>Xem thông tin</span></div>
                                </a>
                            </figure>
                            <div class="wrapper">
                                <small>Chuyên : @doctor.Department.Name</small>
                                <h3>Bác sĩ: @doctor.User.FullName</h3>
                                <p>Tốt nghiệp: @doctor.Education</p>
                                <span class="rating"><i class="icon_star voted"></i><i class="icon_star voted"></i><i class="icon_star voted"></i><i class="icon_star"></i><i class="icon_star"></i> <small>(145)</small></span>
                                <a href="badges.html" data-toggle="tooltip" data-placement="top" data-original-title="Badge Level" class="badge_list_1"><img src="img/badges/badge_2.svg" width="15" height="15" alt=""></a>
                            </div>
                            <ul>
                                <li><a href="@url">Đặt lịch</a> </li>
                            </ul>
                        </div>
                    </div>
                }
            </div>

            <nav aria-label="" class="add_top_20">
                <ul class="pagination pagination-sm">
                    @for (int i = 1; i <= Model.TotalPages; i++)
                    {
                        if (@Model.Page == i)
                        {
                            <li class="page-item active"><a class="page-link" id="doctor-page" href="?page=@i&soft=@soft">@i</a></li>
                        }
                        else
                        {
                            <li class="page-item"><a class="page-link" id="doctor-page" href="?page=@i&soft=@soft">@i</a></li>
                        }
                    }
                    @if (Model.Page < Model.TotalPages)
                    {
                        <li class="page-item">
                            <a class="page-link" id="doctor-page" href="?page=@(Model.Page+1)&soft=@soft">Trang tiếp</a>
                        </li>
                    }
                </ul>
            </nav>
        </div>
    </div>
</div>

SunShineHospital/SunShineHospital/Views/Doctor/Detail.cshtml
@model SunShineHospital.Models.DoctorViewModel

@{
    ViewBag.Title = "Detail";
}

<div id="breadcrumb">
    <div class="container">
        <ul>
            <li><a href="@Url.Action("Index", "Home")">Trang chủ</a></li>
            <li>@Model.User.FullName</li>
        </ul>
    </div>
</div>
		
<div class="container margin_60">
    <div class="row">
        <aside class="col-xl-3 col-lg-4" id="sidebar">
            <div class="box_profile">
                <figure>
                    <img src="@Model.Image" alt="" class="img-fluid">
                </figure>
                <small>Chuyên : @Model.Department.Name</small>
                <h1>Bác sĩ : @Model.User.FullName</h1>
                <span class="rating">
                    <i class="icon_star voted"></i>
                    <i class="icon_star voted"></i>
                    <i class="icon_star voted"></i>
                    <i class="icon_star voted"></i>
                    <i class="icon_star"></i>
                    <small>(145)</small>
                </span>
                <ul class="statistic">
                    <li>@Model.ViewCount Lượt xem</li>
                    <li>0 Bệnh Nhân</li>
                </ul>
                <ul class="contacts">
                    <li><h6>Địa chỉ</h6>@Model.User.Address</li>
                    <li><h6>Tốt nghiệp</h6>@Model.Education</li>
                    <li><h6>Số điện thoại</h6>@Model.User.PhoneNumber</li>
                </ul>
            </div>
        </aside>
        <div class="col-xl-9 col-lg-8">
            <div class="box_general_2 add_bottom_45">
                <div class="main_title_4">
                    <h3><i class="icon_circle-slelected"></i>Chọn ngày, giờ khám</h3>
                </div>

                <div class="row add_bottom_45">
                    <div class="col-lg-7">
                        <div class="form-group">
                            <div id="calendar" data-id="@Model.ID"></div>
                            <ul class="legend">
                                <li><strong></strong>Còn chỗ</li>
                                <li><strong></strong>Kín chỗ</li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-5">
                        <ul class="time_select version_2 add_top_20">
                            <li>
                                <input type="radio" id="radio5" name="radio_time" value="08:30" data-id="@Model.ID">
                                <label for="radio5">08.30 am</label>
                            </li>
                            <li>
                                <input type="radio" id="radio6" name="radio_time" value="09:00" data-id="@Model.ID">
                                <label for="radio6">09.00 am</label>
                            </li>
                            <li>
                                <input type="radio" id="radio1" name="radio_time" value="09:30" data-id="@Model.ID">
                                <label for="radio1">09.30 am</label>
                            </li>
                            <li>
                                <input type="radio" id="radio2" name="radio_time" value="10:00" data-id="@Model.ID">
                                <label for="radio2">10.00 am</label>
                            </li>
                            <li>
                                <input type="radio" id="radio3" name="radio_time" value="10:30" data-id="@Model.ID">
                                <label for="radio3">10.30 am</label>
                            </li>
                            <li>
                                <input type="radio" id="radio4" name="radio_time" value="11:00" data-id="@Model.ID">
                                <label for="radio4">11.00 am</label>
                            </li>

                            <li>
                                <input type="radio" id="radio7" name="radio_time" value="13:30" data-id="@Model.ID">
                                <label for="radio7">01.30 pm</label>
                            </li>
                            <li>
                                <input type="radio" id="radio8" name="radio_time" value="14:00" data-id="@Model.ID">
                                <label for="radio8">02.00 pm</label>
                            </li>
                            <li>
                                <input type="radio" id="radio9" name="radio_time" value="14:30" data-id="@Model.ID">
                                <label for="radio9">02.30 pm</label>
                            </li>
                            <li>
                                <input type="radio" id="radio10" name="radio_time" value="15:00" data-id="@Model.ID">
                                <label for="radio10">03.00 pm</label>
                            </li>
                            <li>
                                <input type="radio" id="radio11" name="radio_time" value="15:30" data-id="@Model.ID">
                                <label for="radio11">03.30 pm</label>
                            </li>
                            <li>
                                <input type="radio" id="radio12" name="radio_time" value="16:00" data-id="@Model.ID">
                                <label for="radio12">04.00 pm</label>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="text-center"><a href="#" class="btn_1 medium" id="btnCreateBooking">Đặt lịch khám </a></div>
            </div>
            <div class="tabs_styled_2">
                <div class="tab-content">
                    <div class="tab-pane fade show active" id="general" role="tabpanel" aria-labelledby="general-tab">
                        <div class="reviews-container">
                            <div class="row">
                                @Html.Action("GetDetail", "Rate", new { id = @Model.ID })
                            </div>
                            <hr>
                            @if (Request.IsAuthenticated)
                            {
                                @Html.Action("Index", "Rate", new { id = @Model.ID })
                            }
                            @Html.Action("Index", "Comment", new { id = @Model.ID })
                        </div>                     
                    </div>  
                </div>
            </div>
        </div>  
    </div>
</div>

SunShineHospital/SunShineHospital/Views/Doctor/GetHotDoctor.cshtml
@using SunShineHospital.Models
@model IEnumerable<DoctorViewModel>
<div class="bg_color_1">
    <div class="container margin_120_95">
        <div class="main_title">
            <h4>Những chuyên gia đầu nghành</h4>
        </div>
        <div class="row">
           @foreach (var doctor in Model)
           {
               var url = "/" + doctor.Alias + ".doc-" + doctor.ID + ".html";
               <div class="col-lg-4 col-md-6">
                   <div class="box_list home">
                       <a href="#0" data-toggle="tooltip" data-placement="top" title="Yêu thích" class="wish_bt"></a>
                       <figure>
                           <a href="@url"><img src="@doctor.Image" class="img-fluid" alt=""></a>
                           <div class="preview"><span>Xem thông tin</span></div>
                       </figure>
                       <div class="wrapper">
                           <small></small>
                           <h3>Bác sĩ  @doctor.User.FullName</h3>  
                           <p>Khoa : @doctor.Department.Name</p>
                           <span class="rating"><i class="icon_star voted"></i><i class="icon_star voted"></i><i class="icon_star voted"></i><i class="icon_star"></i><i class="icon_star"></i> <small>(145)</small></span>
                           <a href="#0" data-toggle="tooltip" data-placement="top" data-original-title="Badge Level" class="badge_list_1"><img src="~/Assets/Client/img/badges/badge_1.svg" width="15" height="15" alt=""></a>
                       </div>
                       <ul>
                           <li><i class="icon-eye-7"></i> @doctor.ViewCount Lượt xem</li>
                           <li><a href="@url">Đặt lịch</a></li>
                       </ul>
                   </div>
               </div>
           }

        </div>
        <p class="text-center add_top_30"><a href="list.html" class="btn_1 medium">Xem tất cả bác sĩ</a></p>
    </div>
</div>